#!/usr/bin/env bash

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Branch name specification:
#
# <branch_name> ::= [<prefix>/] ADFA-<ticket> [-<suffix>]
#
# <prefix>     ::= <alphanumeric_string>
# <ticket>     ::= <digit> {3,5}
# <suffix>     ::= <hyphen> <alphanumeric_string>
#
# <alphanumeric_string> ::= <letter> {<letter> | <digit> | _ | -}*
# <letter>     ::= [a-zA-Z]
# <digit>      ::= [0-9]
# <hyphen>     ::= "-"

if ! [[ "$branch_name" =~ ^([a-zA-Z0-9_-]+\/)?ADFA-[0-9]{3,5}(-[a-zA-Z0-9_-]+)?$ ]]; then
	echo "❌ Error: Branch name '$branch_name' does not conform to the naming policy."
	echo ""
	echo "Please rename the branch to one of the following allowed formats:"
	echo "  - ADFA-123"
	echo "  - ADFA-1234"
	echo "  - ADFA-12345"
	echo "  - feature/ADFA-123"
	echo "  - bugfix/ADFA-9999"
	echo "  - anyprefix/ADFA-12345"
	echo "  - anyprefix/ADFA-12345-additional-context"
	exit 1
fi
